name: Release

on:
  push:
    tags:
      - 'v*.*.*'  # 例如 v1.0.0, v2.1.3

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas openpyxl
    
    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
    
    - name: Create release package
      run: |
        mkdir -p release
        cp adduct_matcher.py release/
        cp README.md release/
        cp Adduct_Table.xlsx release/
        
        # 創建版本資訊檔案
        cat > release/VERSION.txt << EOF
        Adduct Matcher ${{ steps.get_version.outputs.VERSION }}
        Release Date: $(date '+%Y-%m-%d')
        
        ESI加合物比對程式
        自動識別質譜數據中的加合物配對
        EOF
        
        echo "Package contents:"
        ls -lh release/
    
    - name: Create ZIP archive
      run: |
        cd release
        zip -r ../adduct-matcher-${{ steps.get_version.outputs.VERSION }}.zip .
        cd ..
        echo "ZIP created:"
        ls -lh adduct-matcher-*.zip
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          adduct-matcher-*.zip
          release/VERSION.txt
        draft: false
        prerelease: false
        generate_release_notes: true
        body: |
          ## ESI 加合物比對程式 ${{ steps.get_version.outputs.VERSION }}
          
          ### 下載
          下載 `adduct-matcher-${{ steps.get_version.outputs.VERSION }}.zip` 後解壓縮即可使用
          
          ### 使用方法
          ```python
          from adduct_matcher import AdductMatcher
          
          matcher = AdductMatcher(ppm_tolerance=20.0)
          results = matcher.process('your_data.xlsx', rt_tolerance=0.05)
          ```
          
          ### 系統需求
          - Python 3.9+
          - pandas
          - openpyxl
          
          詳細說明請參考 README.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
